/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.angazovanja;

import domen.Angazovanje;
import domen.Projekat;
import domen.Zaposleni;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentKontroler;
import kontroler.KlijentKontrolerAngazovanje;
import kontroler.KlijentKontrolerProjekat;
import kontroler.KlijentKontrolerZaposleni;

/**
 *
 * @author Mihajlo
 */
public class DodajAngazovanjeForma extends javax.swing.JDialog {

    /**
     * Creates new form DodajAngazovanjeForma
     */
    public DodajAngazovanjeForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(null);
            setTitle("Dodavanje angazovanja");
            popuniCmbs();
        } catch (Exception ex) {
            Logger.getLogger(DodajAngazovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbZaposleni = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbProjekat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDatumPocetkaAngazovanja = new javax.swing.JFormattedTextField();
        btnDodajAngazovanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Zaposleni:");

        jLabel2.setText("Projekat:");

        jLabel3.setText("Početak angažovanja:");

        try {
            txtDatumPocetkaAngazovanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##.####.")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnDodajAngazovanje.setText("Dodaj");
        btnDodajAngazovanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAngazovanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDatumPocetkaAngazovanja)
                            .addComponent(cmbProjekat, 0, 262, Short.MAX_VALUE)
                            .addComponent(cmbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajAngazovanje)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProjekat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumPocetkaAngazovanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajAngazovanje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajAngazovanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAngazovanjeActionPerformed
        try{
            Zaposleni zaposleni = (Zaposleni) cmbZaposleni.getSelectedItem();
            Projekat projekat = (Projekat) cmbProjekat.getSelectedItem();

            if (txtDatumPocetkaAngazovanja.getText().isEmpty()) {
                throw new Exception("Niste uneli pocetak angazovanja.");
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            Date datumPocetkaRealizacije = sdf.parse(txtDatumPocetkaAngazovanja.getText());
            
            Angazovanje angazovanje = new Angazovanje(0, projekat, zaposleni, datumPocetkaRealizacije, null);
            KlijentKontrolerAngazovanje.getInstanca().dodajAngazovanje(angazovanje);
            
            cmbZaposleni.setSelectedIndex(0);
            cmbProjekat.setSelectedIndex(0);
            txtDatumPocetkaAngazovanja.setText("");
            
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste dodali angazovanje.");
            
        } catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnDodajAngazovanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAngazovanje;
    private javax.swing.JComboBox<Object> cmbProjekat;
    private javax.swing.JComboBox<Object> cmbZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtDatumPocetkaAngazovanja;
    // End of variables declaration//GEN-END:variables

    private void popuniCmbs() throws Exception {
        cmbZaposleni.removeAllItems();
        LinkedList<Zaposleni> listaZaposlenih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene();
        for (Zaposleni zaposleni : listaZaposlenih) {
            cmbZaposleni.addItem(zaposleni);
        }
        
        cmbProjekat.removeAllItems();
        LinkedList<Projekat> litsaProjekata = KlijentKontrolerProjekat.getInstanca().vratiProjekte();
        for (Projekat projekat : litsaProjekata) {
            cmbProjekat.addItem(projekat);
        }
        
    }
}
