/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.angazovanja;

import domen.Angazovanje;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentKontroler;
import kontroler.KlijentKontrolerAngazovanje;
import modeli.ModelTabeleAngazovanje;

/**
 *
 * @author Mihajlo
 */
public class ObrisiAngazovanjeForma extends javax.swing.JDialog {

    /**
     * Creates new form ObrisiAngazovanjeForma
     */
    ModelTabeleAngazovanje mta;
    public ObrisiAngazovanjeForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(null);
            setTitle("Brisanje angazovanja");
            tblAngazovanje.setAutoCreateRowSorter(true);
            mta = new ModelTabeleAngazovanje();
            tblAngazovanje.setModel(mta);
            popuniTabeluSvimAngazovanjima();
        } catch (Exception ex) {
            Logger.getLogger(ObrisiAngazovanjeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretragaAngazovanje = new javax.swing.JTextField();
        btnPronadjiAngazovanje = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngazovanje = new javax.swing.JTable();
        btnObrisiAngazovanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPronadjiAngazovanje.setText("Pronađi");

        tblAngazovanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAngazovanje);

        btnObrisiAngazovanje.setText("Obriši");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPretragaAngazovanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPronadjiAngazovanje))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiAngazovanje)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaAngazovanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPronadjiAngazovanje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisiAngazovanje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiAngazovanje;
    private javax.swing.JButton btnPronadjiAngazovanje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAngazovanje;
    private javax.swing.JTextField txtPretragaAngazovanje;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluSvimAngazovanjima() throws Exception {
        LinkedList<Angazovanje> listaSvihAngazovanja = KlijentKontrolerAngazovanje.getInstanca().vratiAngazovanja();
        if (listaSvihAngazovanja.size() > 0) {
            ModelTabeleAngazovanje mta = (ModelTabeleAngazovanje) tblAngazovanje.getModel();
            mta.setListaAngazovanje(listaSvihAngazovanja);
        } else if(listaSvihAngazovanja.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ne postoji nijedno angazovanje.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Doslo je do greske prilikom pretrage angazovanja.");
            this.dispose();
        }
    }
}
