/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme.zaposleni;

import domen.Zaposleni;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KlijentKontroler;
import kontroler.KlijentKontrolerZaposleni;
import modeli.ModelTabeleZaposleni;

/**
 *
 * @author Mihajlo
 */
public class ObrisiZaposlenogForma extends javax.swing.JDialog {

    /**
     * Creates new form ObrisiZaposlenogForma
     */
    ModelTabeleZaposleni mtz;
    Zaposleni odabraniZaposleni;
    public ObrisiZaposlenogForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(null);
            setTitle("Brisanje zaposlenog");
            btnObrisiZaposlenog.setEnabled(false);
            tblZaposleni.setAutoCreateRowSorter(true);
            mtz = new ModelTabeleZaposleni();
            tblZaposleni.setModel(mtz);
            popuniTabeluSvimZaposlenim();
        } catch (Exception ex) {
            Logger.getLogger(ObrisiZaposlenogForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPronadjiZaposlenog = new javax.swing.JPanel();
        txtPretragaZaposlenog = new javax.swing.JTextField();
        btnPronadjiZaposlenog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        btnUcitajZaposlenog = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnObrisiZaposlenog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtZaposleniID = new javax.swing.JTextField();
        txtZaposleniIme = new javax.swing.JTextField();
        txtZaposleniPrezime = new javax.swing.JTextField();
        txtZaposleniEmail = new javax.swing.JTextField();
        txtZaposleniDatumZaposlenja = new javax.swing.JTextField();
        txtZaposleniOrganizacionaCelina = new javax.swing.JTextField();
        txtZaposleniRadnoMesto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPronadjiZaposlenog.setBorder(javax.swing.BorderFactory.createTitledBorder("Pronađi zaposlenog"));

        btnPronadjiZaposlenog.setText("Pronađi");
        btnPronadjiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPronadjiZaposlenogActionPerformed(evt);
            }
        });

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZaposleni);

        btnUcitajZaposlenog.setText("Učitaj zaposlenog");
        btnUcitajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajZaposlenogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPronadjiZaposlenogLayout = new javax.swing.GroupLayout(panelPronadjiZaposlenog);
        panelPronadjiZaposlenog.setLayout(panelPronadjiZaposlenogLayout);
        panelPronadjiZaposlenogLayout.setHorizontalGroup(
            panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                        .addComponent(txtPretragaZaposlenog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPronadjiZaposlenog))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPronadjiZaposlenogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUcitajZaposlenog)))
                .addContainerGap())
        );
        panelPronadjiZaposlenogLayout.setVerticalGroup(
            panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPronadjiZaposlenogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPronadjiZaposlenogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretragaZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPronadjiZaposlenog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnUcitajZaposlenog)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Učitani zaposleni"));

        btnObrisiZaposlenog.setText("Obriši zaposlenog");
        btnObrisiZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZaposlenogActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("Email:");

        jLabel5.setText("Datum zaposlenja:");

        jLabel6.setText("Organizaciona celina:");

        jLabel7.setText("Radno mesto:");

        txtZaposleniID.setEditable(false);

        txtZaposleniIme.setEditable(false);

        txtZaposleniPrezime.setEditable(false);

        txtZaposleniEmail.setEditable(false);
        txtZaposleniEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZaposleniEmailActionPerformed(evt);
            }
        });

        txtZaposleniDatumZaposlenja.setEditable(false);
        txtZaposleniDatumZaposlenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZaposleniDatumZaposlenjaActionPerformed(evt);
            }
        });

        txtZaposleniOrganizacionaCelina.setEditable(false);

        txtZaposleniRadnoMesto.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiZaposlenog))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZaposleniID)
                                    .addComponent(txtZaposleniIme)
                                    .addComponent(txtZaposleniPrezime)
                                    .addComponent(txtZaposleniEmail)
                                    .addComponent(txtZaposleniDatumZaposlenja)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtZaposleniOrganizacionaCelina)
                                    .addComponent(txtZaposleniRadnoMesto, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtZaposleniID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtZaposleniIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZaposleniPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtZaposleniEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtZaposleniDatumZaposlenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtZaposleniOrganizacionaCelina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtZaposleniRadnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnObrisiZaposlenog)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPronadjiZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPronadjiZaposlenog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelPronadjiZaposlenog.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPronadjiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPronadjiZaposlenogActionPerformed
        try {
            String pretraga = txtPretragaZaposlenog.getText();
            LinkedList<Zaposleni> listaZaposlenihIzPretrage = KlijentKontrolerZaposleni.getInstanca().pronadjiPaVratiZaposlene(pretraga);
            ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
            mtz.setListaZaposlenih(listaZaposlenihIzPretrage);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnPronadjiZaposlenogActionPerformed

    private void btnObrisiZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZaposlenogActionPerformed
        try {
            KlijentKontrolerZaposleni.getInstanca().obrisiZaposlenog(odabraniZaposleni);
            LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene();
            if (listaSvihZaposlnih.size() > 0) {
                ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                mtz.setListaZaposlenih(listaSvihZaposlnih);
            } else if(listaSvihZaposlnih.size() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Obrisali ste sve zaposlene. Ne postoji nijedan zaposleni za prikaz.");
                this.dispose();
            }
            JOptionPane.showMessageDialog(rootPane, "Uspesno ste obrisali zaposlenog: " + odabraniZaposleni);
            txtZaposleniID.setText("");
            txtZaposleniIme.setText("");
            txtZaposleniPrezime.setText("");
            txtZaposleniEmail.setText("");
            txtZaposleniDatumZaposlenja.setText("");
            txtZaposleniOrganizacionaCelina.setText("");
            txtZaposleniRadnoMesto.setText("");
            btnObrisiZaposlenog.setEnabled(false);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Zaposleni " + odabraniZaposleni + " nije obrisan.", "Doslo je do greske!", JOptionPane.ERROR_MESSAGE);

        }
        
        
    }//GEN-LAST:event_btnObrisiZaposlenogActionPerformed

    private void txtZaposleniEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZaposleniEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZaposleniEmailActionPerformed

    private void txtZaposleniDatumZaposlenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZaposleniDatumZaposlenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZaposleniDatumZaposlenjaActionPerformed

    private void btnUcitajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajZaposlenogActionPerformed
        try{
            int red = tblZaposleni.getSelectedRow();
            if (red == -1) {
                JOptionPane.showMessageDialog(this, "Odaberite zaposlenog iz tabele.");
            } else {
                ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                odabraniZaposleni = mtz.vratiOdabranogZaposlenog(red);
                Zaposleni ucitaniZaposleni = KlijentKontrolerZaposleni.getInstanca().ucitajZaposlenog(odabraniZaposleni);
                popuniPodatkeUcitanogZaposlenog(ucitaniZaposleni);
                btnObrisiZaposlenog.setEnabled(true);
            }
        } catch (Exception ex){
            try {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Zaposleni " + odabraniZaposleni + " je obrisan.", "Doslo je do greske.", JOptionPane.INFORMATION_MESSAGE);
                LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene();
                if (listaSvihZaposlnih.size() > 0) {
                    ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
                    mtz.setListaZaposlenih(listaSvihZaposlnih);
                } else if(listaSvihZaposlnih.size() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Obrisali ste sve zaposlene. Ne postoji nijedan zaposleni za prikaz.");
                    this.dispose();
                }
            } catch (Exception ex1) {
                ex1.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUcitajZaposlenogActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiZaposlenog;
    private javax.swing.JButton btnPronadjiZaposlenog;
    private javax.swing.JButton btnUcitajZaposlenog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPronadjiZaposlenog;
    private javax.swing.JTable tblZaposleni;
    private javax.swing.JTextField txtPretragaZaposlenog;
    private javax.swing.JTextField txtZaposleniDatumZaposlenja;
    private javax.swing.JTextField txtZaposleniEmail;
    private javax.swing.JTextField txtZaposleniID;
    private javax.swing.JTextField txtZaposleniIme;
    private javax.swing.JTextField txtZaposleniOrganizacionaCelina;
    private javax.swing.JTextField txtZaposleniPrezime;
    private javax.swing.JTextField txtZaposleniRadnoMesto;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluSvimZaposlenim() throws Exception {
        LinkedList<Zaposleni> listaSvihZaposlnih = KlijentKontrolerZaposleni.getInstanca().vratiZaposlene();
        if (listaSvihZaposlnih.size() > 0) {
            ModelTabeleZaposleni mtz = (ModelTabeleZaposleni) tblZaposleni.getModel();
            mtz.setListaZaposlenih(listaSvihZaposlnih);
        } else if(listaSvihZaposlnih.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Ne postoji nijedan zaposleni.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Doslo je do greske prilikom pretrage zaposlenih.");
            this.dispose();
        }
    }

    private void popuniPodatkeUcitanogZaposlenog(Zaposleni ucitaniZaposleni) {
        txtZaposleniID.setText(String.valueOf(ucitaniZaposleni.getZaposleniId()));
        txtZaposleniIme.setText(ucitaniZaposleni.getIme());
        txtZaposleniPrezime.setText(ucitaniZaposleni.getPrezime());
        txtZaposleniEmail.setText(ucitaniZaposleni.getEmail());
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        txtZaposleniDatumZaposlenja.setText(sdf.format(ucitaniZaposleni.getDatumZaposlenja()));
        txtZaposleniOrganizacionaCelina.setText(ucitaniZaposleni.getOrganizacionaCelina().getNazivOrganizacioneCeline());
        txtZaposleniRadnoMesto.setText(ucitaniZaposleni.getRadnoMesto().getNazivRadnogMesta());
    }
}
